questions =  [
    {"id": 0, "question": "It is acceptable that CEOs earn hundreds of times the salary of the average worker, as CEOs are more valuable and harder to replace.", "effects": {"right": 1}},
    {"id": 1, "question": "My ideal society would feature laissez faire economics with little if any interference in the free market.", "effects": {"right": 1}},
    {"id": 2, "question": "Taxation is theft.", "effects": {"right": 1}},
    {"id": 3, "question": "Public welfare should be greatly reduced or abolished entirely.", "effects": {"right": 1}},
    {"id": 4, "question": "Privatisation of industry is generally better and more efficient than nationalisation.", "effects": {"right": 1}},
    {"id": 5, "question": "Corporation tax should be kept relatively low in order to remain competitive in the global economy.", "effects": {"right": 1}},
    {"id": 6, "question": "We should try to strengthen local industry and prevent job outsourcing with methods such as tariffs on foreign trade and subsidisation of local producers.", "effects": {"right": -1}},
    {"id": 7, "question": "Workers should control the means of production.", "effects": {"right": -1}},
    {"id": 8, "question": "Wealth inequality is a serious problem.", "effects": {"right": -1}},
    {"id": 9, "question": "University should be subsidised to not require any tuition fees.", "effects": {"right": -1}},
    {"id": 10, "question": "I support universal healthcare.", "effects": {"right": -1}},
    {"id": 11, "question": "Private property should be abolished.", "effects": {"right": -1}},
    {"id": 12, "question": "Key industries, such as postal and utility services, should be publicly-owned.", "effects": {"right": -1}},
    {"id": 13, "question": "We should not allow people to become billionaires.", "effects": {"right": -1}},
    {"id": 14, "question": "I support a widespread redistribution of wealth and resources to ensure greater economic equality.", "effects": {"right": -1}},
    {"id": 15, "question": "", "effects": {"auth": 1}},
    {"id": 16, "question": "", "effects": {"auth": 1}},
    {"id": 17, "question": "", "effects": {"auth": 1}},
    {"id": 18, "question": "", "effects": {"auth": 1}},
    {"id": 19, "question": "", "effects": {"auth": 1}},
    {"id": 20, "question": "", "effects": {"auth": 1}},
    {"id": 21, "question": "", "effects": {"auth": 1}},
    {"id": 22, "question": "", "effects": {"auth": 1}},
    {"id": 23, "question": "", "effects": {"auth": -1}},
    {"id": 24, "question": "", "effects": {"auth": -1}},
    {"id": 25, "question": "", "effects": {"auth": -1}},
    {"id": 26, "question": "", "effects": {"auth": -1}},
    {"id": 27, "question": "", "effects": {"auth": -1}},
    {"id": 28, "question": "", "effects": {"auth": -1}},
    {"id": 29, "question": "", "effects": {"auth": -1}},
    {"id": 30, "question": "", "effects": {"prog": 1}},
    {"id": 31, "question": "", "effects": {"prog": 1}},
    {"id": 32, "question": "", "effects": {"prog": 1}},
    {"id": 33, "question": "", "effects": {"prog": 1}},
    {"id": 34, "question": "", "effects": {"prog": 1}},
    {"id": 35, "question": "", "effects": {"prog": 1}},
    {"id": 36, "question": "", "effects": {"prog": 1}},
    {"id": 37, "question": "", "effects": {"prog": 1}},
    {"id": 38, "question": "", "effects": {"prog": -1}},
    {"id": 39, "question": "", "effects": {"prog": -1}},
    {"id": 40, "question": "", "effects": {"prog": -1}},
    {"id": 41, "question": "", "effects": {"prog": -1}},
    {"id": 42, "question": "", "effects": {"prog": -1}},
    {"id": 43, "question": "", "effects": {"prog": -1}},
    {"id": 44, "question": "", "effects": {"prog": -1}},
    {"id": 45, "question": "", "effects": {"prog": -1}},
	{"id": 46, "question": "", "effects": {"prog": -1}},
    {"id": 47, "question": "", "effects": {"prog": -1}},
    {"id": 48, "question": "", "effects": {"prog": -1}},
    {"id": 49, "question": "", "effects": {"prog": -1}},
    {"id": 50, "question": "", "effects": {"prog": -1}}
];
